version: '3.0'

networks:
  zabbix:
    driver:
      bridge

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.0-ubuntu-latest
    ports: 
      - 10051:10051
    restart: always
    environment:
      DB_SERVER_HOST: zabbix-mysql
      DB_SERVER_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_ENABLE_SNMP_TRAPS: "true"
    volumes:
      - volumes_from: zabbix-snmptraps
    networks:
      - zabbix
